# Menentukan versi docker-compose yang digunakan, yaitu 3.7
version: "3.7"
# Mendefinisikan service yang akan dibuat
services:
 
   
# Mendefinisikan service ke-2 yaitu item-db
  item-db:
   # Menggunakan image mongo:3
    image: mongo:3
    # Memakai volume bernama app-db dengan target /data/db
    volumes: 
    - app-db:/data/db
    # Mendefiniskan restart policy yang jika container gagal berjalan, akan dilakukan restart otomatis
    restart: on-failure

# Mendefinisikan service ke-1 yaitu item-app
  item-app:
    # item-app akan memakai image container bernama item-app dengan tag:v1
    image: elffree/item-app:v1
    # Mengekspos ke port:80 ke host dan port:8080 ke container
    ports: 
    - 80:8080
    # Mendefinisikan working directory yaitu /app
    working_dir: /app
    # Mendefiniskan volume yang dipakai, yaitu pada working directory yang sudah dibuat sebelumnya
    volumes: 
    - ./:/app
     # Mendefiniskan memastikan item-app hanya berjalan setelah item-db diluncurkan.
    depends_on: 
    - item-db
    # Mendefiniskan restart policy yang jika container gagal berjalan, akan dilakukan restart otomatis
    restart: on-failure
# Membuat satu buah volume bernama app-db
volumes:
  app-db: